<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Bnp</RootNamespace>
        <AssemblyName>bnp</AssemblyName>
        <ApplicationIcon>Assets\BNP.ico</ApplicationIcon>
        <IsAotCompatible>true</IsAotCompatible>
        <PublishAot>true</PublishAot>
        <PublishSelfContained>true</PublishSelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <UseCurrentRuntimeIdentifier>true</UseCurrentRuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Bnp.Core\Bnp.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\BNP.ico" />
        <AvaloniaResource Include="..\..\fonts\Inconsolata.ttf" Link="Assets\Fonts\Inconsolata.ttf" />
        <EmbeddedResource Include="Localization\copy.*.json">
            <WithCulture>false</WithCulture>
            <LogicalName>BNP.Localization.%(Filename)%(Extension)</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="AvaloniaRichEditor" />
        <PackageReference Include="Lucide.Avalonia" />
        <PackageReference Include="Microsoft.Data.Sqlite" />
    </ItemGroup>
</Project>